  language: python
  python:
    - "2.7"
    - "3.5"
    - "3.6"

  sudo: required

  addons:
    apt:
      packages:
        libjs-mathjax

  before_install:
    - pip install nose2 pandas

  script:
    - python -m nose2 -v
    - cd doc
    - pip install -r source/requirements.txt
    - make html
